import PostsLists from "@/components/PostsLists";
import PostsPagination from "@/components/PostsPagination";
import { getPostsPagination, totalPages } from "@/utils/PostsPaginationUtil";

export const metadata = {
  title: "Lista de todos los post",
  description: "Description posts - Generated by create next app",
};

const Posts = () => {
  const { currentPosts } = getPostsPagination();

  return (
    <div>
      <h1 className="text-center my-4 text-3xl">Posts</h1>
      <div className="grid gap-4">
        <PostsLists posts={currentPosts} />
        {totalPages > 1 && <PostsPagination totalPages={totalPages} />}
      </div>
    </div>
  );
};
export default Posts;
