import { allPosts, Post } from "contentlayer/generated";

import PostsLists from "@/components/PostsLists";
import PostsPagination from "@/components/PostsPagination";
import { getPagination } from "@/utils/pagination";

const posts: Post[] = allPosts.sort((a, b) => b.date.localeCompare(a.date));

export const metadata = {
  title: "Lista de todos los post",
  description: "Description posts - Generated by create next app",
};

const Posts = () => {
  const { currentPosts, totalPages } = getPagination(posts);

  return (
    <div>
      <div className="grid gap-4">
        <PostsLists posts={currentPosts} />
        {totalPages > 1 && <PostsPagination totalPages={totalPages} />}
      </div>
    </div>
  );
};
export default Posts;
